# -*- coding: utf-8 -*-
"""Análisis de Inversión 8.5.0ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10mahxOFdb9JIg1k6b9gvu4PyXCwkg1kd

# Activos operacionales.
"""

import pandas as pd
import numpy as np
import yfinance as yf
from statsmodels.tsa.holtwinters import Holt
import datetime
import warnings
import requests # Import the requests library
from scipy.stats import percentileofscore, spearmanr
from tabulate import tabulate
#warnings.simplefilter(action='ignore', category=FutureWarning)


Activos_historicos=['NVDA', 'BBVA', 'WMT',"CAT", "MU", "SNDK", "WELL", "WDC", "GEV", "GOOGL", "LITE", "AMD", "DELL"]
ETFs_historicos=["QQQM", 'VDC', 'GLD']

"""# Aduanas

## Filtro activos
"""

# ==========================================
# CONFIGURACIÓN INICIAL
# ==========================================
R_f = 0.045
periodos = [1, 2, 3, 5, 10]

def aduana_integral():
    activo_input = input("Activo a evaluar: ").upper()
    activos_actuales = Activos_historicos

    end = datetime.date.today()
    start_5y = end - datetime.timedelta(days=3*365 + 10)

    # 1. DESCARGA ÚNICA (Ajustada por dividendos/splits)
    todo = [activo_input] + activos_actuales
    try:
        data = yf.download(todo, start=start_5y, end=end, progress=False, auto_adjust=True)['Close']
    except:
        print("❌ Error en la descarga de datos.")
        return

    if data[activo_input].isnull().all():
        print(f"❌ Error: Ticker '{activo_input}' no encontrado o sin datos.")
        return

    # 2. CÁLCULO DE MÉTRICAS HISTÓRICAS
    resultados_finales = []
    for p in periodos:
        dias = p * 252
        df_p = data[activo_input].tail(dias).dropna()

        if len(df_p) < 100: continue

        rets_log = np.log(df_p / df_p.shift(1)).dropna()
        rend_anual = np.exp(rets_log.mean() * 252) - 1
        sigma_anual = rets_log.std() * np.sqrt(252)
        sr = (rend_anual - R_f) / sigma_anual

        # MDD sobre precios ajustados
        rolling_max = df_p.cummax()
        mdd = ((df_p - rolling_max) / rolling_max).min()

        resultados_finales.append({
            "Activo": activo_input,
            "Periodo": f"{p}A",
            "SR": sr,
            "Retorno %": rend_anual * 100,
            "Sigma %": sigma_anual * 100,
            "MDD %": mdd * 100
        })

    # 3. IMPRESIÓN DE PIZARRA DE VALIDACIÓN
    df_pizarra = pd.DataFrame(resultados_finales)
    print(f"\n{'='*75}")
    print(f" PIZARRA DE VALIDACIÓN HISTÓRICA: {activo_input}")
    print(f"{'='*75}")
    print(tabulate(df_pizarra, headers='keys', tablefmt='psql', floatfmt=".2f"))

    # 4. ANÁLISIS DE DIVERSIFICACIÓN
    print("\n--- ANÁLISIS DE DIVERSIFICACIÓN (Correlación 2Y) ---")
    data_2y = data.tail(3*252).pct_change().dropna()
    corr_series = data_2y.corr()[activo_input].loc[activos_actuales]

    df_corr = pd.DataFrame(corr_series)
    print(tabulate(df_corr, headers=['Ticker', activo_input], tablefmt='psql', floatfmt=".2f"))

    # Interpretación de Correlación
    promedio_corr = corr_series.mean()
    print(f"\nCorrelación Promedio: {promedio_corr:.2f}")

    if promedio_corr > 0.20:
        print("⚠️ ALERTA: Este activo es muy similar a tu cartera actual.")
    elif promedio_corr <= 0.20:
        print("✅ DIVERSIFICACIÓN: Este activo aporta movimientos distintos.")

    for ticker, corr_val in corr_series.items():
        if abs(corr_val) > 0.75:
            print(f"⚠️ ALERTA: Correlación muy fuerte ({corr_val:.2f}) con {ticker}.")
        elif abs(corr_val) < 0.20:
            print(f"✅ DIVERSIFICACIÓN: Correlación muy baja ({corr_val:.2f}) con {ticker}.")

    # 5. VEREDICTO FINAL CON DOBLE FILTRO
    print(f"\n{'='*75}")
    print(f" RESULTADO FINAL DEL ANÁLISIS")
    print(f"{'='*75}")

    # Filtro 1: Consistencia SR
    aprobados_sr = sum(1 for x in resultados_finales if x['SR'] > 1.0)
    # Filtro 2: Eficiencia de Riesgo (Retorno > |MDD| en el promedio de los periodos evaluados)
    # Exigimos que al menos en el corto (1A) y medio plazo (3A) el retorno supere al susto
    eficiencia_1a = resultados_finales[0]['Retorno %'] > abs(resultados_finales[0]['MDD %'])
    eficiencia_3a = any(x['Retorno %'] > abs(x['MDD %']) for x in resultados_finales if x['Periodo'] == '3A')

    print(f"1. Consistencia SR (>1.0): {aprobados_sr}/5 periodos.")
    print(f"2. Eficiencia 1A (Retorno > |MDD|): {'✅ PASA' if eficiencia_1a else '❌ FALLA'}")
    print(f"3. Eficiencia 3A (Retorno > |MDD|): {'✅ PASA' if eficiencia_3a else '❌ FALLA'}")

    if aprobados_sr >= 3 and eficiencia_1a and eficiencia_3a:
        print(f"\nVEREDICTO: ✅ {activo_input} ES APTO PARA EL MCMC")
    else:
        print(f"\nVEREDICTO: ❌ {activo_input} RECHAZADO")
        if aprobados_sr < 3:
            print("- Razón: No cumple la consistencia de Sharpe Ratio mínima.")
        if not (eficiencia_1a and eficiencia_3a):
            print("- Razón: Riesgo Asimétrico (La caída máxima supera al rendimiento esperado).")
    print(f"{'='*75}\n")

# Ejecutar programa
aduana_integral()

"""## Filtro ETFs

# Optimización de portafolio
"""

# =============================================================================
# SISTEMA MAESTRO 8.5.0
# =============================================================================

# semilla para reproducibilidad
np.random.seed(42)

# =============================================================================
# 1. PARÁMETROS INICIALES Y ADQUISICIÓN DE DATOS
# =============================================================================
print("="*120)
print("\n" + f"SISTEMA MAESTRO 8.5.0 (Metropolis-Hastings & Filtro 5 Zonas)")
print("\n" + "="*120)

valor_inicio_mes = float(input("Saldo mes anterior (USD): "))
valor_actual = float(input("Saldo actual (USD): "))

# Listas base de activos
acciones = Activos_historicos
etfs = ETFs_historicos
todos = acciones + etfs

posiciones = {a: float(input(f"   USD actuales en {a}: ")) for a in todos}

end = datetime.date.today()
start = end - datetime.timedelta(days=450)
raw_data = yf.download(todos, start=start, end=end, progress=False, auto_adjust=True)['Close']

data_limpia = pd.DataFrame()
for a in todos:
    data_limpia[a] = raw_data[a].ffill().tail(252)

R_data = np.log(data_limpia / data_limpia.shift(1)).dropna()

# =============================================================================
# 2. MÉTRICAS DEL PORTAFOLIO HISTÓRICO
# =============================================================================
pesos_act = np.array([posiciones[a] for a in todos]) / valor_actual

r_anual_ind = []
for a in todos:
    serie_act = data_limpia[a].dropna()
    r_anual_ind.append((serie_act.iloc[-1] / serie_act.iloc[0]) - 1 if len(serie_act) > 1 else 0.0)

r_anual_ind = np.array(r_anual_ind)
cov_mat_anual = (R_data.cov() * 252).values
rp_hist = np.sum(pesos_act * r_anual_ind)

MAR_anual = 0.045
MAR_diario = MAR_anual / 252
ret_p = (R_data * pesos_act).sum(axis=1)
downside_dev_hist = np.sqrt(np.mean(np.minimum(0, ret_p - MAR_diario)**2)) * np.sqrt(252)
sortino_hist = (rp_hist - MAR_anual) / downside_dev_hist if downside_dev_hist > 0 else 0

cum_ret = np.exp(ret_p.cumsum())
mdd_hist = ((cum_ret - cum_ret.cummax()) / cum_ret.cummax()).min()

ganancia_usd = valor_actual - valor_inicio_mes
ganancia_pct = ganancia_usd / valor_inicio_mes if valor_inicio_mes > 0 else 0
cosecha_potencial = ganancia_usd * 0.20
total_cosecha = cosecha_potencial if cosecha_potencial > 50 else 0
cap_mcmc = valor_actual - total_cosecha

# =============================================================================
# 3. FILTRO ESTRUCTURAL DE RESIDUOS (5 ZONAS CON REGLA DE FLEXIBILIDAD)
# =============================================================================
residuos_dic = {}
for a in todos:
    series_semanal = data_limpia[a].resample('W').last().ffill().dropna()
    model = Holt(series_semanal, initialization_method="estimated").fit(smoothing_level=0.2, smoothing_trend=0.05)
    residuos = series_semanal - model.fittedvalues
    residuos_dic[a] = percentileofscore(residuos, residuos.iloc[-1])

# Lógica de flexibilidad adaptativa para garantizar el mínimo de 8 activos
umbral_z2 = 60.0
def calcular_aptos(u_z2):
    acc_ok = [a for a in acciones if residuos_dic[a] > 40.0 or (residuos_dic[a] > u_z2 and residuos_dic[a] <= 95.0)]
    etf_ok = [a for a in etfs if residuos_dic[a] > 40.0 or (residuos_dic[a] > u_z2 and residuos_dic[a] <= 95.0)]
    return acc_ok, etf_ok

acciones_elegibles, etfs_elegibles = calcular_aptos(umbral_z2)
if (len(acciones_elegibles) + len(etfs_elegibles)) < 8:
    umbral_z2 = 50.0  # Relajación del suelo por criterio de diversificación
    acciones_elegibles, etfs_elegibles = calcular_aptos(umbral_z2)

print("\n" + "="*120)
print(" 1. MÉTRICAS DEL PORTAFOLIO (PTMP)")
print("-" * 120)
print(f" Rendimiento Anualizado: {rp_hist:.2%}")
print(f" Downside Dev (Riesgo):  {downside_dev_hist:.2%}")
print(f" Sortino Ratio:          {sortino_hist:.2f}")
print(f" Max Drawdown:           {mdd_hist:.2%}")
print(f" Ganancia Neta Mes:      ${ganancia_usd:,.2f} USD ({ganancia_pct:.2%})")
print(f" COSECHA A RETIRAR:      ${total_cosecha:,.2f} USD")
print(f" CAPITAL REBALANCEO:     ${cap_mcmc:,.2f} USD")
print("-" * 120)
print(f"-> Activos aptos para compras/mantenimiento: {len(acciones_elegibles)} Acciones, {len(etfs_elegibles)} ETFs (Suelo Z2 a {umbral_z2}%)")
print(f"-> Activos en Liquidación Defensiva (Z5): {[a for a in todos if residuos_dic[a] <= 1.0]}")

# =============================================================================
# 4. MOTOR DE OPTIMIZACIÓN MCMC (METROPOLIS-HASTINGS + SEMILLA HEURÍSTICA)
# =============================================================================
print("\n[Calculando Cadenas de Markov (Metropolis-Hastings v8.5.2) para optimización PMPT...]")

def sortino_objective(w, R_matrix):
    port_ret = R_matrix.dot(w)
    dd = np.sqrt(np.mean(np.minimum(0, port_ret - (0.045/252))**2)) * np.sqrt(252)
    ret_anual = np.exp(port_ret.mean() * 252) - 1
    return (ret_anual - 0.045) / dd if dd > 0 else -100

def check_constraints_v852(w, posiciones, cap_mcmc, acciones, etfs, todos, residuos_dic):
    # Validar normalización absoluta
    if abs(np.sum(w) - 1.0) > 1e-4:
        return False

    # 1. Filtro estricto de pesos activos y cardinalidad mínima
    activos_en_cartera = np.sum(w > 0.005)
    if activos_en_cartera < 6:
        return False

    for i, peso in enumerate(w):
        if peso > 0.005 and (peso < 0.03 or peso > 0.20):
            return False

    # 2. Mix de Silos
    peso_acc = np.sum([w[todos.index(a)] for a in acciones])
    peso_etf = np.sum([w[todos.index(a)] for a in etfs])
    if not (0.60 <= peso_acc <= 0.95) or not (0.05 <= peso_etf <= 0.40): # Changed 0.20 to 0.05 for peso_etf min
        return False

    # 3. Restricciones del Semáforo de 5 Zonas (Validación Vectorial)
    for i, a in enumerate(todos):
        p_rank = residuos_dic[a]
        peso_actual_nom = posiciones[a] / cap_mcmc

        # Z1, Z3, Z4: No pueden recibir capital nuevo (Techo duro)
        if p_rank > 95.0 or (1.0 < p_rank <= 60.0):
            if w[i] > peso_actual_nom + 0.001:
                return False

        # Z5: Liquidación Absoluta
        if p_rank <= 1.0 and w[i] > 0.005:
            return False

    return True

# --- GENERADOR DE SEMILLA HEURÍSTICO ---
# Construye un portafolio de origen matemáticamente inquebrantable
w_nom = np.array([posiciones[a] for a in todos]) / cap_mcmc

def generar_semilla_valida():
    for _ in range(100000):
        w = np.zeros(len(todos))

        # 1. Asignar capital a las zonas restringidas (Z1, Z3, Z4) sin superar el límite nominal
        for i, a in enumerate(todos):
            p_rank = residuos_dic[a]
            max_w = min(w_nom[i], 0.20)
            if p_rank > 95.0 or (1.0 < p_rank <= 60.0):
                if max_w >= 0.03:
                    # Mantenemos parcial o totalmente la posición para no romper inercia
                    w[i] = np.random.uniform(0.03, max_w)

        # 2. Asignar capital a la zona libre (Z2) para cumplir cardinalidad
        z2_idx = [i for i, a in enumerate(todos) if 60.0 < residuos_dic[a] <= 95.0]
        activos_actuales = np.sum(w > 0)
        faltantes = max(0, 6 - activos_actuales)

        if len(z2_idx) < faltantes:
            continue # Imposible cumplir cardinalidad con el mercado actual

        # Elegir cuántos activos de Z2 activar
        k_z2 = np.random.randint(faltantes, len(z2_idx) + 1) if len(z2_idx) > faltantes else faltantes
        if k_z2 > 0:
            elegidos_z2 = np.random.choice(z2_idx, k_z2, replace=False)
            for i in elegidos_z2:
                w[i] = 0.03 # Base mínima para evitar exclusión

        # 3. Empujar la suma al 100% financiando exclusivamente los activos Z2
        suma = np.sum(w)
        if suma > 1.0:
            continue # Nos excedimos con los mínimos

        falta = 1.0 - suma
        if k_z2 > 0 and falta > 0:
            dist = np.random.dirichlet(np.ones(k_z2)) * falta
            for j, idx in enumerate(elegidos_z2):
                w[idx] += dist[j]

        # Evaluamos pureza matemática de la semilla
        if check_constraints_v852(w, posiciones, cap_mcmc, acciones, etfs, todos, residuos_dic):
            return w

    return None

w_current = generar_semilla_valida()
if w_current is None:
    raise ValueError("El Generador Heurístico no pudo encontrar una semilla que cumpla todas las reglas estructurales. Revisa la cardinalidad permitida.")

best_weights = w_current.copy()
best_sortino = sortino_objective(w_current, R_data.values)

# --- SIMULACIÓN METROPOLIS-HASTINGS GUIADA ---
iterations = 500000
R_matrix = R_data.values
sigma_salto = 0.015

for _ in range(iterations):
    salto = np.random.normal(0, sigma_salto, len(todos))
    w_proposal = w_current + salto

    # Pre-filtro: Mantener en cero lo que no existe en el estado actual
    w_proposal = np.where(w_current == 0, 0.0, w_proposal)
    w_proposal = np.clip(w_proposal, 0, 0.20)

    if np.sum(w_proposal) > 0:
        w_proposal /= np.sum(w_proposal)

    if check_constraints_v852(w_proposal, posiciones, cap_mcmc, acciones, etfs, todos, residuos_dic):
        sortino_prop = sortino_objective(w_proposal, R_matrix)

        if sortino_prop > best_sortino:
            best_sortino = sortino_prop
            best_weights = w_proposal.copy()

        # Temperatura de aceptación de saltos
        if sortino_prop >= sortino_objective(w_current, R_matrix):
            w_current = w_proposal.copy()
        else:
            diff = sortino_prop - sortino_objective(w_current, R_matrix)
            if np.random.uniform(0, 1) < np.exp(diff / 0.02):
                w_current = w_proposal.copy()

w_final = best_weights

# =============================================================================
# 5. GENERACIÓN DE MOVIMIENTOS Y PANEL (FILTRO DE INERCIA DEL 10%)
# =============================================================================
movimientos_candidatos = []
for i, a in enumerate(todos):
    peso_obj = w_final[i]
    val_obj_usd = peso_obj * cap_mcmc
    dif = val_obj_usd - posiciones[a]

    # Filtro de Inercia de Negocio: Solo operar si el cambio supera el 10% de la posición actual o si se liquida por completo
    umbral_operativo = 0.10 * posiciones[a] if posiciones[a] > 0 else 1.0

    if abs(dif) >= umbral_operativo or (peso_obj == 0 and posiciones[a] > 0):
        p_rank = residuos_dic[a]
        zona = "Z1 Cosecha 🟢" if p_rank > 95 else "Z2 Inercia + 🟡" if p_rank > 60 else "Z3 Neutral ⚪" if p_rank > 40 else "Z4 Inercia - 🟠" if p_rank > 1 else "Z5 Liquidar 🔴"

        movimientos_candidatos.append({
            'activo': a, 'val_act': posiciones[a], 'p_rank': p_rank, 'zona': zona,
            'peso_obj': peso_obj, 'val_obj_usd': val_obj_usd, 'dif': dif
        })

movimientos_candidatos.sort(key=lambda x: abs(x['dif']), reverse=True)
top_movimientos = movimientos_candidatos[:10]

tabla_accion = []
for mov in top_movimientos:
    tabla_accion.append([
        mov['activo'], f"${mov['val_act']:,.1f}", f"{mov['p_rank']:.1f}%", mov['zona'],
        f"{mov['peso_obj']:.0%}", f"${mov['val_obj_usd']:,.0f}", f"${mov['dif']:+,.0f}"
    ])

print("\n" + "="*120)
print(" 2. PANEL DE ACCIÓN TÁCTICA (TOP 10 MOVIMIENTOS - REGLA DE INERCIA 10%)")
print("-" * 120)
headers = ['Activo', 'Val Act', 'Residuo', 'Semáforo', 'Peso Obj', 'Val Obj USD', 'Acción USD']
print(tabulate(tabla_accion, headers=headers, tablefmt='fancy_grid'))

print(f"\n ESTADO DE OPERACIONES (RACIONAL):")
print(f" -> Movimientos estratégicos recomendados: {len(tabla_accion)} de 10")

# =============================================================================
# 6. RESUMEN POST-AJUSTE (PMPT)
# =============================================================================
rp_post = np.sum(w_final * r_anual_ind)
ret_p_post = R_matrix.dot(w_final)
dd_post = np.sqrt(np.mean(np.minimum(0, ret_p_post - MAR_diario)**2)) * np.sqrt(252)
sr_post = (rp_post - 0.045) / dd_post if dd_post > 0 else 0

ret_p_post_series = pd.Series(np.exp(ret_p_post.cumsum()))
mdd_post = ((ret_p_post_series - ret_p_post_series.cummax()) / ret_p_post_series.cummax()).min()

sigmas = np.sqrt(np.diag(cov_mat_anual))
bernstein = np.sum(w_final * (sigmas**2)) - (dd_post**2)
corr_spearman, _ = spearmanr(R_data)

pct_acc = np.sum([w_final[todos.index(a)] for a in acciones])
pct_etf = np.sum([w_final[todos.index(a)] for a in etfs])
activos_activos = np.sum(w_final > 0)

print("\n" + "="*120)
print(" 3. RESUMEN POST-AJUSTE (PMPT)")
print("-" * 120)
print(f" Rendimiento Esperado:            {rp_post:.2%}")
print(f" Downside Dev (Riesgo a la Baja): {dd_post:.2%}")
print(f" Sortino Ratio Esperado:          {sr_post:.2f}")
print(f" Max Drawdown:                    {mdd_post:.2%}")
print(f" Índice de Bernstein (PMPT):      {bernstein:.4f}")
print(f" Correlación Media (Spearman):    {np.mean(corr_spearman):.4f}")
print("-" * 120)
print(f" Verificación Silos: Acciones {pct_acc:.1%} / ETFs {pct_etf:.1%}")
print(f" Activos en Portafolio: {activos_activos}")
print("="*120)

"""# Pruebas

"""

# ==========================================
# EXPLORADOR DE SP500
# ==========================================
# 1. BUSQUEDA AUTOMÁTICA DE ACTIVOS
# ==========================================
def obtener_universo_sp500():
    print("Descargando lista actualizada del SP500...")
    url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        table = pd.read_html(response.text)
    except requests.exceptions.RequestException as e:
        print(f"Error fetching data from Wikipedia: {e}")
        return []

    df = table[0]
    tickers = df['Symbol'].str.replace('.', '-', regex=False).tolist()
    return tickers

# ==========================================
# 2. FILTRO ESTOCÁSTICO
# ==========================================
def escaneo_masivo(universo, activos_actuales):
    candidatos_aptos = []
    end = datetime.date.today()

    # CORRECCIÓN 1: 400 días calendario para asegurar >252 días hábiles bursátiles
    start = end - datetime.timedelta(days=3*252)

    todos_los_tickers = list(set(universo + activos_actuales))

    print(f"Descargando datos históricos de {len(todos_los_tickers)} activos...")
    data = yf.download(todos_los_tickers, start=start, end=end, interval="1d", progress=False)['Close']

    activos_validos = [a for a in activos_actuales if a in data.columns and not data[a].dropna().empty]
    if len(activos_validos) < len(activos_actuales):
        print(f"Aviso: Algunos de tus activos no trajeron datos. Serán omitidos del cálculo de correlación.")

    print("Procesando modelos Holt y fronteras de riesgo...")

    for ticker in universo:
        try:
            if ticker not in data.columns: continue

            series = data[ticker].dropna()

            # Ahora sí pasará el filtro porque descargamos 400 días
            if len(series) < 250: continue

            # --- FILTRO A: TENDENCIA DE HOLT ---
            model = Holt(series, initialization_method="estimated").fit(smoothing_level=0.8, smoothing_trend=0.2)

            # CORRECCIÓN 3: Usamos tu misma lógica del Sistema Maestro (más robusta)
            slope_actual = model.fittedvalues.iloc[-1] - model.fittedvalues.iloc[-2]

            if slope_actual <= 0: continue

            # --- FILTRO B: SHARPE RATIO ---
            # Tomamos solo los últimos 252 días hábiles para medir el último año exacto
            series_1y = series.tail(252)
            rets_log = np.log(series_1y / series_1y.shift(1)).dropna()
            rend_anual = np.exp(rets_log.mean() * 252) - 1
            sigma_anual = rets_log.std() * np.sqrt(252)

            if sigma_anual == 0: continue
            sr = (rend_anual - 0.0359) / sigma_anual

            # CORRECCIÓN 2: Bajamos el Sharpe Ratio a un nivel realista (1.0 es excelente)
            if sr < 1.8: continue

            # --- FILTRO C: DIVERSIFICACIÓN (CORRELACIÓN) ---
            if activos_validos:
                data_corr = data[[ticker] + activos_validos].dropna(how='any').tail(252)
                if len(data_corr) < 50: continue

                matriz_corr = data_corr.pct_change().dropna().corr()
                corr_media = matriz_corr[ticker].loc[activos_validos].mean()

                if corr_media > 0.60: continue
            else:
                corr_media = 0.0

            candidatos_aptos.append({
                'Ticker': ticker,
                'Sharpe': round(sr, 2),
                'Retorno_Anual': f"{rend_anual:.1%}",
                'Corr_Media': round(corr_media, 2),
                'Trend': "✅ Alcista"
            })

        except Exception as e:
            # Ahora si falla algo interno, al menos no lo silencia completamente si necesitas debuggear
            # print(f"Error procesando {ticker}: {e}")
            continue

    return pd.DataFrame(candidatos_aptos)

# ==========================================
# 3. EJECUCIÓN DEL PROGRAMA
# ==========================================
if __name__ == "__main__":
    mis_activos = Activos_historicos + ETFs_historicos

    universo_tickers = obtener_universo_sp500()

    # TIP DE INGENIERO: Puedes probar con los primeros 50 para ver resultados rápidos
    # universo_tickers = universo_tickers[:50]

    df_final = escaneo_masivo(universo_tickers, mis_activos)

    print("\n" + "="*70)
    print(" 🎯 LISTA DE CANDIDATOS FILTRADOS (LISTOS PARA V8.0)")
    print("="*70)

    if df_final.empty:
        print("Ningún activo superó la estricta Aduana en este ciclo.")
    else:
        print(df_final.sort_values(by='Sharpe', ascending=False).to_string(index=False))

def aduana_etfs_v46():
    print(f"\n{'='*85}")
    print(f" 🛡️ ADUANA DE ETFs V2.0 - COHESIÓN Y EFICIENCIA")
    print(f"{'='*85}")

    # --- CONTEXTO GLOBAL ---
    mis_acciones = Activos_historicos
    mis_etfs_existentes = ETFs_historicos

    etf_input = input("ETF a evaluar: ").upper()
    benchmark = "VOO"
    end = datetime.date.today()
    start_5y = end - datetime.timedelta(days=5*365 + 10)

    try:
        t = yf.Ticker(etf_input)
        info = t.info

        # --- DATOS FUNDAMENTALES ---
        exp_ratio = info.get('expenseRatio')
        if exp_ratio is None:
            print(f"⚠️ No se detectó costo anual para {etf_input} automáticamente.")
            exp_ratio = float(input(f"   Por favor, ingresa el costo de la App (ej. 0.05): ")) / 100

        div_yield = info.get('trailingAnnualDividendYield') or info.get('yield') or 0
        aum = (info.get('totalAssets') or info.get('marketCap') or 0) / 1e9

        # Universo completo para matriz de correlación
        all_tickers = list(set([etf_input, benchmark] + mis_acciones + mis_etfs_existentes))
        data_raw = yf.download(all_tickers, start=start_5y, end=end, progress=False, auto_adjust=True)['Close'].ffill()

    except Exception as e:
        print(f"❌ Error crítico: {e}")
        return

    # --- MÉTRICAS DE INGENIERÍA (Duelo de Sharpe) ---
    def calcular_metricas(ticker):
        df = data_raw[ticker].tail(252).dropna() # Ventana de 1 año para decisión mensual
        ret = (df.iloc[-1] / df.iloc[0]) - 1
        vol = np.log(df / df.shift(1)).std() * np.sqrt(252)
        sharpe = (ret - 0.035) / vol if vol > 0 else 0
        mdd = ((df - df.cummax()) / df.cummax()).min()
        return ret, vol, sharpe, mdd

    ret_in, vol_in, sharpe_in, mdd_in = calcular_metricas(etf_input)

    # --- CÁLCULO DE CORRELACIONES (1 AÑO) ---
    returns_1y = np.log(data_raw.tail(252) / data_raw.tail(252).shift(1)).dropna()

    # 1. vs Acciones (70%)
    corr_acc_avg = np.mean([returns_1y[etf_input].corr(returns_1y[acc]) for acc in mis_acciones])

    # 2. vs Otros ETFs (30%) - Duelo de Eficiencia
    max_corr_etf = 0
    rival_nombre = "N/A"
    es_sustituto = False
    duelo_msg = ""

    otros_etfs = [e for e in mis_etfs_existentes if e != etf_input]
    if otros_etfs:
        corrs = {e: returns_1y[etf_input].corr(returns_1y[e]) for e in otros_etfs}
        rival_nombre = max(corrs, key=corrs.get)
        max_corr_etf = corrs[rival_nombre]

        if max_corr_etf > 0.80: # Umbral de redundancia técnica
            _, _, sharpe_rival, _ = calcular_metricas(rival_nombre)
            if sharpe_in > (sharpe_rival * 1.05): # Margen del 5% para justificar el cambio
                es_sustituto = True
                duelo_msg = f"🚀 SUPERIOR: {etf_input} ({sharpe_in:.2f}) vs {rival_nombre} ({sharpe_rival:.2f})"
            else:
                duelo_msg = f"📉 INFERIOR: {etf_input} ({sharpe_in:.2f}) vs {rival_nombre} ({sharpe_rival:.2f})"

    # --- PANTALLA DE RESULTADOS ---
    print(f"\n📊 FUNDAMENTALES:")
    print(f"- Patrimonio (AUM): ${aum:.2f}B {'✅' if aum > 1 else '❌'}")
    print(f"- Gasto Anual: {exp_ratio*100:.3f}% {'✅' if exp_ratio < 0.0035 else '⚠️'}")

    print(f"\n🔗 COHESIÓN Y CORRELACIÓN:")
    print(f"- Corr. Avg vs Acciones: {corr_acc_avg:.2f} {'⚠️ ESPEJO' if corr_acc_avg > 0.75 else '✅ ORTOGONAL'}")
    if otros_etfs:
        print(f"- Rival más parecido: {rival_nombre} (Corr: {max_corr_etf:.2f})")
        if max_corr_etf > 0.80:
            print(f"⚔️ DUELO DE EFICIENCIA: {duelo_msg}")

    # --- VEREDICTO DE INGENIERÍA ---
    f1_aum = aum > 1.0
    f2_costo = exp_ratio < 0.0035
    f3_vol = vol_in < 0.35 # Volatilidad menor al 35% para el bloque de seguridad
    f4_orto = corr_acc_avg < 0.75
    f5_duelo = not (max_corr_etf > 0.80 and not es_sustituto)

    print(f"\n{'='*85}")
    print(f"1. Liquidez: {'✅' if f1_aum else '❌'} | 2. Costo: {'✅' if f2_costo else '❌'} | 3. Sigma < 35%: {'✅' if f3_vol else '❌'}")
    print(f"4. Ortogonalidad: {'✅' if f4_orto else '⚠️'} | 5. Eficiencia Relativa: {'✅' if f5_duelo else '❌'}")

    if all([f1_aum, f2_costo, f3_vol, f5_duelo]):
        if es_sustituto:
            print(f"\nVEREDICTO: 🔄 REEMPLAZO SUGERIDO. Saca {rival_nombre} y mete {etf_input}.")
        elif max_corr_etf > 0.80:
            print(f"\nVEREDICTO: ❌ RECHAZADO POR REDUNDANCIA INEFICIENTE.")
        else:
            print(f"\nVEREDICTO: ✅ {etf_input} ES APTO (NUEVA DIVERSIFICACIÓN).")
    else:
        print(f"\nVEREDICTO: ❌ {etf_input} RECHAZADO.")
        if not f5_duelo: print(f"   -> MOTIVO: Es redundante con {rival_nombre} y tiene menor Sharpe Ratio.")

aduana_etfs_v46()